//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLoginMaster
    {
        public int LoginId { get; set; }
        public string LoginName { get; set; }
        public string LoginEmailId { get; set; }
        public string LoginPassword { get; set; }
        public string LoginMobile { get; set; }
    }
}
