//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExpertMaster()
        {
            this.ExpertSkillMasters = new HashSet<ExpertSkillMaster>();
        }
    
        public int ExpertId { get; set; }
        public string ExpertName { get; set; }
        public string ExpertPassword { get; set; }
        public string ExpertEmailId { get; set; }
        public string ExpertMobile { get; set; }
        public string Occupation { get; set; }
        public decimal Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertSkillMaster> ExpertSkillMasters { get; set; }
    }
}
