//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductMaster()
        {
            this.CartMasters = new HashSet<CartMaster>();
        }
    
        public int ProductId { get; set; }
        public string Title { get; set; }
        public decimal MyPrice { get; set; }
        public decimal OriginalPrice { get; set; }
        public bool IsSecondHand { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string Desccription { get; set; }
        public bool IsSold { get; set; }
        public string ImageUrl { get; set; }
        public int refCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartMaster> CartMasters { get; set; }
        public virtual CategoryMaster CategoryMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
